### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by dhAlcojor**
Fix a typo in the `git clone` command in the README.md file.

It says to use `--branch base` when it should be `--branch multimodule`.

### CODE REVIEW

**Comment by dhAlcojor** [comment]
> Hi! Why would you want to clone multimodule instead of base?

To get the multimodule project instead of the basic, monomodule, one.

**Comment by JoseAlcerreca** [comment]
I don't see what's wrong with that so closing for now.

**Comment by dhAlcojor** [comment]
Awesome

**Comment by JoseAlcerreca** [comment]
I'm totally open to it but you're not explaining why you'd want that one. The `base` one is a lot simpler for a quick playground project, which is what most people use this project for. We can provide commands for both branches, but I wouldn't default to multimodule.

**Pull request closed without merging**
